baseURL = "https://www.aaronbatilo.dev"
title = "Aaron Batilo"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "The website of someone who owns a light up keyboard"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about"
    weight = 10

  [[menu.main]]
    identifier = "resume"
    name = "resume"
    title = "resume"
    url = "/resume.pdf"
    weight = 20

  [[menu.main]]
    identifier = "linkedin"
    name = "linkedin"
    title = "linkedin"
    url = "https://www.linkedin.com/in/abatilo"
    weight = 30

  [[menu.main]]
    identifier = "github"
    name = "github"
    title = "github"
    url = "https://www.github.com/abatilo"
    weight = 40

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
